-- Run table-schema.sql before this file.

INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('AAPL', 'Apple Inc.', 'Equity', 'USD', TRUE, 185.3200);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('MSFT', 'Microsoft Corporation', 'Equity', 'USD', TRUE, 402.1100);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('GOOGL', 'Alphabet Inc.', 'Equity', 'USD', TRUE, 141.8700);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('TSLA', 'Tesla Inc.', 'Equity', 'USD', TRUE, 238.4400);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('VUSA', 'Vanguard S&P 500 ETF', 'ETF', 'GBP', TRUE, 84.2200);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('US10Y', 'United States 10 Year Bond', 'Bond', 'USD', TRUE, 98.7500);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('BTC', 'Bitcoin', 'Crypto', 'USD', TRUE, 42000.0000);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('ETH', 'Ethereum', 'Crypto', 'USD', TRUE, 2450.0000);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('IBM', 'International Business Machines', 'Equity', 'USD', TRUE, 176.2500);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('BND', 'Vanguard Total Bond Market ETF', 'ETF', 'USD', TRUE, 72.4800);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('ORCL', 'Oracle Corporation', 'Equity', 'USD', TRUE, 118.4500);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('AMZN', 'Amazon.com Inc.', 'Equity', 'USD', TRUE, 174.8800);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('META', 'Meta Platforms Inc.', 'Equity', 'USD', TRUE, 485.2200);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('NFLX', 'Netflix Inc.', 'Equity', 'USD', TRUE, 612.3000);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('NVDA', 'NVIDIA Corporation', 'Equity', 'USD', TRUE, 875.5000);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('JPM', 'JPMorgan Chase & Co.', 'Equity', 'USD', TRUE, 182.7500);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('V', 'Visa Inc.', 'Equity', 'USD', TRUE, 279.6300);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('JNJ', 'Johnson & Johnson', 'Equity', 'USD', TRUE, 157.4200);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('KO', 'Coca-Cola Company', 'Equity', 'USD', TRUE, 60.1500);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('PEP', 'PepsiCo Inc.', 'Equity', 'USD', TRUE, 169.8800);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('WMT', 'Walmart Inc.', 'Equity', 'USD', TRUE, 171.3000);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('DIS', 'Walt Disney Company', 'Equity', 'USD', TRUE, 111.2500);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('BA', 'Boeing Company', 'Equity', 'USD', TRUE, 205.4000);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('XOM', 'Exxon Mobil Corporation', 'Equity', 'USD', TRUE, 103.7800);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('CVX', 'Chevron Corporation', 'Equity', 'USD', TRUE, 151.2200);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('PFE', 'Pfizer Inc.', 'Equity', 'USD', TRUE, 27.5400);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('ADBE', 'Adobe Inc.', 'Equity', 'USD', TRUE, 548.1000);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('CRM', 'Salesforce Inc.', 'Equity', 'USD', TRUE, 296.7500);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('INTC', 'Intel Corporation', 'Equity', 'USD', TRUE, 43.6800);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('CSCO', 'Cisco Systems Inc.', 'Equity', 'USD', TRUE, 50.9200);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('SPY', 'SPDR S&P 500 ETF', 'ETF', 'USD', TRUE, 505.6000);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('QQQ', 'Invesco QQQ ETF', 'ETF', 'USD', TRUE, 438.7500);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('IWM', 'iShares Russell 2000 ETF', 'ETF', 'USD', TRUE, 201.3400);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('EFA', 'iShares MSCI EAFE ETF', 'ETF', 'USD', TRUE, 78.4400);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('AGG', 'iShares Core US Aggregate Bond ETF', 'ETF', 'USD', TRUE, 97.1200);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('LQD', 'iShares Investment Grade Bond ETF', 'ETF', 'USD', TRUE, 108.3000);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('GLD', 'SPDR Gold Shares', 'ETF', 'USD', TRUE, 188.6500);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('SLV', 'iShares Silver Trust', 'ETF', 'USD', TRUE, 22.8700);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('US2Y', 'United States 2 Year Bond', 'Bond', 'USD', TRUE, 99.2500);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('US5Y', 'United States 5 Year Bond', 'Bond', 'USD', TRUE, 98.9600);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('US30Y', 'United States 30 Year Bond', 'Bond', 'USD', TRUE, 97.8800);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('DE10Y', 'Germany 10 Year Bond', 'Bond', 'EUR', TRUE, 96.7400);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('SOL', 'Solana', 'Crypto', 'USD', TRUE, 108.2500);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('XRP', 'XRP', 'Crypto', 'USD', TRUE, 0.6200);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('ADA', 'Cardano', 'Crypto', 'USD', TRUE, 0.5800);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('DOT', 'Polkadot', 'Crypto', 'USD', TRUE, 7.4200);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('AVAX', 'Avalanche', 'Crypto', 'USD', TRUE, 36.1800);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('LINK', 'Chainlink', 'Crypto', 'USD', TRUE, 18.9500);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('MATIC', 'Polygon', 'Crypto', 'USD', FALSE, 0.8900);
INSERT INTO instruments (symbol, instrument_name, asset_class, currency, is_tradable, price) VALUES ('LTC', 'Litecoin', 'Crypto', 'USD', TRUE, 72.6000);


INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Alice', 'Chen', 'alice.chen@example.com', 'seed-hash-client-001', '417-82-6394', '312-748-9056', 25000.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Ben', 'Whitfield', 'ben.whitfield@example.com', 'seed-hash-client-002', '583-14-7269', '646-203-8174', 18500.5000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Chidi', 'Nwosu', 'chidi.nwosu@example.com', 'seed-hash-client-003', '096-47-3815', '718-394-2601', 42000.7500, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Diane', 'Kowalski', 'diane.kowalski@example.com', 'seed-hash-client-004', '741-63-2058', '925-681-4370', 15750.2500, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Elliot', 'Park', 'elliot.park@example.com', 'seed-hash-client-005', '268-95-7140', '503-817-2946', 31800.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Farida', 'Haidari', 'farida.haidari@example.com', 'seed-hash-client-006', '905-28-4617', '847-159-6302', 22750.1250, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Grace', 'Lindqvist', 'grace.lindqvist@example.com', 'seed-hash-client-007', '352-76-9081', '274-936-5810', 10900.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Hassan', 'Malik', 'hassan.malik@example.com', 'seed-hash-client-008', '619-04-8372', '436-702-1958', 50300.8750, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Isla', 'Fraser', 'isla.fraser@example.com', 'seed-hash-client-009', '827-51-3649', '591-824-7036', 27500.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Jamal', 'Ferris', 'jamal.ferris@example.com', 'seed-hash-client-010', '134-89-5726', '809-315-4728', 19250.6250, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Karen', 'Adams', 'karen.adams@example.com', 'seed-hash-client-011', '476-32-8105', '672-481-9305', 21500.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Liam', 'Baker', 'liam.baker@example.com', 'seed-hash-client-012', '790-16-2483', '358-907-1624', 22850.5000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Maya', 'Carter', 'maya.carter@example.com', 'seed-hash-client-013', '215-68-9437', '741-268-5093', 30100.7500, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Noah', 'Davis', 'noah.davis@example.com', 'seed-hash-client-014', '638-27-1509', '286-593-7140', 16750.2500, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Olivia', 'Evans', 'olivia.evans@example.com', 'seed-hash-client-015', '904-35-7821', '915-407-6382', 34200.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Priya', 'Foster', 'priya.foster@example.com', 'seed-hash-client-016', '371-80-5264', '430-786-2519', 24750.1250, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Quinn', 'Garcia', 'quinn.garcia@example.com', 'seed-hash-client-017', '562-49-3187', '763-129-8450', 11900.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Rosa', 'Harris', 'rosa.harris@example.com', 'seed-hash-client-018', '183-72-6405', '508-674-2319', 41300.8750, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Sam', 'Ibrahim', 'sam.ibrahim@example.com', 'seed-hash-client-019', '849-06-2573', '691-305-7824', 28500.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Tina', 'Johnson', 'tina.johnson@example.com', 'seed-hash-client-020', '427-91-0368', '824-517-3069', 20250.6250, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Uma', 'Khan', 'uma.khan@example.com', 'seed-hash-client-021', '695-38-1742', '279-846-5130', 21750.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Victor', 'Lewis', 'victor.lewis@example.com', 'seed-hash-client-022', '308-57-9261', '934-208-6751', 23900.5000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Wendy', 'Moore', 'wendy.moore@example.com', 'seed-hash-client-023', '972-41-6830', '516-793-0428', 31100.7500, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Xavier', 'Nelson', 'xavier.nelson@example.com', 'seed-hash-client-024', '154-83-7096', '687-431-9250', 17750.2500, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Yara', 'Owens', 'yara.owens@example.com', 'seed-hash-client-025', '836-25-4917', '402-865-1379', 35200.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Zane', 'Patel', 'zane.patel@example.com', 'seed-hash-client-026', '249-70-5386', '758-214-9630', 25750.1250, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Aaron', 'Quinn', 'aaron.quinn@example.com', 'seed-hash-client-027', '581-36-9042', '321-679-0845', 12900.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Bella', 'Rivera', 'bella.rivera@example.com', 'seed-hash-client-028', '763-08-2154', '846-530-2179', 42300.8750, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Caleb', 'Scott', 'caleb.scott@example.com', 'seed-hash-client-029', '426-97-5813', '209-754-6813', 29500.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Dalia', 'Turner', 'dalia.turner@example.com', 'seed-hash-client-030', '017-64-8395', '973-420-5681', 21250.6250, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Evan', 'Usman', 'evan.usman@example.com', 'seed-hash-client-031', '894-12-3670', '614-837-2059', 22750.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Fiona', 'Vega', 'fiona.vega@example.com', 'seed-hash-client-032', '235-79-6408', '785-162-4390', 24900.5000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Gavin', 'White', 'gavin.white@example.com', 'seed-hash-client-033', '618-43-0725', '439-706-1825', 32100.7500, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Holly', 'Xu', 'holly.xu@example.com', 'seed-hash-client-034', '349-86-1572', '862-315-7049', 18750.2500, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Ivan', 'Young', 'ivan.young@example.com', 'seed-hash-client-035', '750-29-4836', '527-948-3160', 36200.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Julia', 'Zimmerman', 'julia.zimmerman@example.com', 'seed-hash-client-036', '182-54-7960', '604-271-9583', 26750.1250, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Kofi', 'Anderson', 'kofi.anderson@example.com', 'seed-hash-client-037', '907-31-6258', '318-754-6209', 13900.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Lena', 'Brown', 'lena.brown@example.com', 'seed-hash-client-038', '463-18-9704', '791-406-2385', 43300.8750, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Marco', 'Clark', 'marco.clark@example.com', 'seed-hash-client-039', '526-84-1307', '856-239-7140', 30500.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Nadia', 'Dixon', 'nadia.dixon@example.com', 'seed-hash-client-040', '074-59-2861', '467-982-1503', 22250.6250, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Owen', 'Ellis', 'owen.ellis@example.com', 'seed-hash-client-041', '681-23-7450', '930-518-2746', 23750.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Paula', 'Franklin', 'paula.franklin@example.com', 'seed-hash-client-042', '315-96-8027', '275-841-6093', 25900.5000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Reza', 'Green', 'reza.green@example.com', 'seed-hash-client-043', '842-07-5196', '719-360-4285', 33100.7500, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Sara', 'Hall', 'sara.hall@example.com', 'seed-hash-client-044', '196-73-4085', '583-927-1460', 19750.2500, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Tom', 'Irwin', 'tom.irwin@example.com', 'seed-hash-client-045', '734-25-8619', '408-671-2539', 37200.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Usha', 'Jones', 'usha.jones@example.com', 'seed-hash-client-046', '459-82-1706', '946-205-7381', 27750.1250, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Victor', 'King', 'victor.king@example.com', 'seed-hash-client-047', '028-64-9371', '631-874-2095', 14900.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Willow', 'Long', 'willow.long@example.com', 'seed-hash-client-048', '573-09-4826', '287-519-6430', 44300.8750, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Yusuf', 'Martin', 'yusuf.martin@example.com', 'seed-hash-client-049', '861-45-2037', '754-136-9280', 31500.0000, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO clients (first_name, last_name, email, password_hash, ssn, phone_number, account_balance, created_at) VALUES ('Zoe', 'Norris', 'zoe.norris@example.com', 'seed-hash-client-050', '392-78-6145', '820-463-1759', 23250.6250, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));

INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Avery', 'Stone', 'avery.stone@admin.com', 'seed-hash-admin-001', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Jordan', 'Reed', 'jordan.reed@admin.com', 'seed-hash-admin-002', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Morgan', 'Blake', 'morgan.blake@admin.com', 'seed-hash-admin-003', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Taylor', 'Wells', 'taylor.wells@admin.com', 'seed-hash-admin-004', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Riley', 'Grant', 'riley.grant@admin.com', 'seed-hash-admin-005', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Casey', 'Young', 'casey.young@admin.com', 'seed-hash-admin-006', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Jamie', 'Cole', 'jamie.cole@admin.com', 'seed-hash-admin-007', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Parker', 'Frost', 'parker.frost@admin.com', 'seed-hash-admin-008', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Sydney', 'Mills', 'sydney.mills@admin.com', 'seed-hash-admin-009', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Drew', 'Hart', 'drew.hart@admin.com', 'seed-hash-admin-010', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Alex', 'Adams', 'alex.adams@admin.com', 'seed-hash-admin-011', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Blair', 'Baker', 'blair.baker@admin.com', 'seed-hash-admin-012', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Cameron', 'Carter', 'cameron.carter@admin.com', 'seed-hash-admin-013', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Devon', 'Davis', 'devon.davis@admin.com', 'seed-hash-admin-014', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Emery', 'Evans', 'emery.evans@admin.com', 'seed-hash-admin-015', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Frankie', 'Foster', 'frankie.foster@admin.com', 'seed-hash-admin-016', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Gray', 'Garcia', 'gray.garcia@admin.com', 'seed-hash-admin-017', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Harper', 'Harris', 'harper.harris@admin.com', 'seed-hash-admin-018', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Indigo', 'Ibrahim', 'indigo.ibrahim@admin.com', 'seed-hash-admin-019', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Jules', 'Johnson', 'jules.johnson@admin.com', 'seed-hash-admin-020', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Kendall', 'Khan', 'kendall.khan@admin.com', 'seed-hash-admin-021', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Logan', 'Lewis', 'logan.lewis@admin.com', 'seed-hash-admin-022', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Micah', 'Moore', 'micah.moore@admin.com', 'seed-hash-admin-023', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Nico', 'Nelson', 'nico.nelson@admin.com', 'seed-hash-admin-024', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Oakley', 'Owens', 'oakley.owens@admin.com', 'seed-hash-admin-025', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Phoenix', 'Patel', 'phoenix.patel@admin.com', 'seed-hash-admin-026', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Reese', 'Quinn', 'reese.quinn@admin.com', 'seed-hash-admin-027', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Shawn', 'Rivera', 'shawn.rivera@admin.com', 'seed-hash-admin-028', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Terry', 'Scott', 'terry.scott@admin.com', 'seed-hash-admin-029', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Val', 'Turner', 'val.turner@admin.com', 'seed-hash-admin-030', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Wren', 'Usman', 'wren.usman@admin.com', 'seed-hash-admin-031', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Yael', 'Vega', 'yael.vega@admin.com', 'seed-hash-admin-032', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Zion', 'White', 'zion.white@admin.com', 'seed-hash-admin-033', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Ash', 'Xu', 'ash.xu@admin.com', 'seed-hash-admin-034', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Brook', 'Young', 'brook.young@admin.com', 'seed-hash-admin-035', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Chris', 'Zimmerman', 'chris.zimmerman@admin.com', 'seed-hash-admin-036', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Dana', 'Anderson', 'dana.anderson@admin.com', 'seed-hash-admin-037', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Erin', 'Brown', 'erin.brown@admin.com', 'seed-hash-admin-038', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Finley', 'Clark', 'finley.clark@admin.com', 'seed-hash-admin-039', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Gale', 'Dixon', 'gale.dixon@admin.com', 'seed-hash-admin-040', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Hope', 'Ellis', 'hope.ellis@admin.com', 'seed-hash-admin-041', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Ira', 'Franklin', 'ira.franklin@admin.com', 'seed-hash-admin-042', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Jesse', 'Green', 'jesse.green@admin.com', 'seed-hash-admin-043', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Kris', 'Hall', 'kris.hall@admin.com', 'seed-hash-admin-044', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Lee', 'Irwin', 'lee.irwin@admin.com', 'seed-hash-admin-045', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Max', 'Jones', 'max.jones@admin.com', 'seed-hash-admin-046', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Nell', 'King', 'nell.king@admin.com', 'seed-hash-admin-047', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Omar', 'Long', 'omar.long@admin.com', 'seed-hash-admin-048', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Pia', 'Martin', 'pia.martin@admin.com', 'seed-hash-admin-049', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));
INSERT INTO admins (first_name, last_name, email, password_hash, created_at) VALUES ('Quincy', 'Norris', 'quincy.norris@admin.com', 'seed-hash-admin-050', CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'));

INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (1, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 22238.4000, 1, 120, 'ACCEPTED', 185.3200);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (2, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 24126.6000, 2, 60, 'ACCEPTED', 402.1100);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (3, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 4937.5000, 6, 50, 'PENDING', 98.7500);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (1, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'SELL', 7444.0000, 1, 40, 'ACCEPTED', 186.1000);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (4, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 3546.7500, 3, 25, 'ACCEPTED', 141.8700);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (5, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 25266.0000, 5, 300, 'REJECTED', 84.2200);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (2, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'SELL', 8091.0000, 2, 20, 'ACCEPTED', 404.5500);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (6, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 21000.0000, 7, 1, 'PENDING', 42000.0000);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (3, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 1978.0000, 6, 20, 'FAILED', 98.9000);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (7, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 3576.6000, 4, 15, 'ACCEPTED', 238.4400);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (11, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 11845.0000, 11, 100, 'ACCEPTED', 118.4500);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (12, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 17488.0000, 12, 100, 'PENDING', 174.8800);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (13, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 9704.4000, 13, 20, 'ACCEPTED', 485.2200);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (14, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 12246.0000, 14, 20, 'ACCEPTED', 612.3000);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (15, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 8755.0000, 15, 10, 'PENDING', 875.5000);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (16, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'SELL', 1827.5000, 16, 10, 'REJECTED', 182.7500);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (17, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 2796.3000, 17, 10, 'REJECTED', 279.6300);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (18, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 1574.2000, 18, 10, 'ACCEPTED', 157.4200);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (19, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 1203.0000, 19, 20, 'PENDING', 60.1500);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (20, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'SELL', 1698.8000, 20, 10, 'REJECTED', 169.8800);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (21, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 1713.0000, 21, 10, 'ACCEPTED', 171.3000);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (22, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 1112.5000, 22, 10, 'FAILED', 111.2500);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (23, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 2054.0000, 23, 10, 'ACCEPTED', 205.4000);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (24, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'SELL', 1512.2000, 24, 10, 'PENDING', 151.2200);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (25, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 1377.0000, 25, 50, 'ACCEPTED', 27.5400);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (26, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 5481.0000, 26, 10, 'ACCEPTED', 548.1000);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (27, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 2967.5000, 27, 10, 'PENDING', 296.7500);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (28, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'SELL', 436.8000, 28, 10, 'REJECTED', 43.6800);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (29, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 509.2000, 29, 10, 'ACCEPTED', 50.9200);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (30, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 5056.0000, 30, 10, 'PENDING', 505.6000);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (31, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 4387.5000, 31, 10, 'ACCEPTED', 438.7500);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (32, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'SELL', 2013.4000, 32, 10, 'REJECTED', 201.3400);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (33, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 784.4000, 33, 10, 'REJECTED', 78.4400);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (34, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 971.2000, 34, 10, 'ACCEPTED', 97.1200);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (35, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 1083.0000, 35, 10, 'PENDING', 108.3000);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (36, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'SELL', 1886.5000, 36, 10, 'REJECTED', 188.6500);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (37, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 1143.5000, 37, 50, 'ACCEPTED', 22.8700);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (38, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 992.5000, 38, 10, 'FAILED', 99.2500);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (39, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 989.6000, 39, 10, 'ACCEPTED', 98.9600);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (40, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'SELL', 978.8000, 40, 10, 'PENDING', 97.8800);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (41, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 967.4000, 41, 10, 'ACCEPTED', 96.7400);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (42, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 1082.5000, 42, 10, 'ACCEPTED', 108.2500);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (43, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 62.0000, 43, 100, 'PENDING', 0.6200);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (44, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'SELL', 58.0000, 44, 100, 'REJECTED', 0.5800);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (45, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 742.0000, 45, 100, 'REJECTED', 7.4200);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (46, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 1809.0000, 46, 50, 'ACCEPTED', 36.1800);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (47, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 947.5000, 47, 50, 'PENDING', 18.9500);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (48, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 89.0000, 48, 100, 'ACCEPTED', 0.8900);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (49, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'SELL', 726.0000, 49, 10, 'REJECTED', 72.6000);
INSERT INTO orders (client_id, order_timestamp, order_type, total_cost, instrument_id, quantity, status, price) VALUES (50, CURRENT_TIMESTAMP - (random() * INTERVAL '10 years'), 'BUY', 1452.0000, 50, 20, 'FAILED', 72.6000);

INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (1, 1, 1, 80, 185.3200);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (2, 2, 2, 40, 402.1100);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (3, 3, 6, 0, 98.7500);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (4, 4, 3, 25, 141.8700);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (5, 5, 5, 0, 84.2200);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (6, 6, 7, 0, 42000.0000);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (7, 7, 4, 15, 238.4400);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (8, 8, 8, 0, 2450.0000);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (9, 9, 9, 0, 176.2500);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (10, 10, 10, 0, 72.4800);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (11, 11, 11, 100, 118.4500);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (12, 12, 12, 0, 174.8800);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (13, 13, 13, 20, 485.2200);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (14, 14, 14, 20, 612.3000);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (15, 15, 15, 0, 875.5000);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (16, 16, 16, 0, 182.7500);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (17, 17, 17, 0, 279.6300);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (18, 18, 18, 10, 157.4200);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (19, 19, 19, 0, 60.1500);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (20, 20, 20, 0, 169.8800);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (21, 21, 21, 10, 171.3000);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (22, 22, 22, 0, 111.2500);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (23, 23, 23, 10, 205.4000);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (24, 24, 24, 0, 151.2200);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (25, 25, 25, 50, 27.5400);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (26, 26, 26, 10, 548.1000);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (27, 27, 27, 0, 296.7500);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (28, 28, 28, 0, 43.6800);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (29, 29, 29, 10, 50.9200);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (30, 30, 30, 0, 505.6000);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (31, 31, 31, 10, 438.7500);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (32, 32, 32, 0, 201.3400);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (33, 33, 33, 0, 78.4400);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (34, 34, 34, 10, 97.1200);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (35, 35, 35, 0, 108.3000);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (36, 36, 36, 0, 188.6500);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (37, 37, 37, 50, 22.8700);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (38, 38, 38, 0, 99.2500);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (39, 39, 39, 10, 98.9600);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (40, 40, 40, 0, 97.8800);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (41, 41, 41, 10, 96.7400);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (42, 42, 42, 10, 108.2500);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (43, 43, 43, 0, 0.6200);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (44, 44, 44, 0, 0.5800);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (45, 45, 45, 0, 7.4200);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (46, 46, 46, 50, 36.1800);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (47, 47, 47, 0, 18.9500);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (48, 48, 48, 100, 0.8900);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (49, 49, 49, 0, 72.6000);
INSERT INTO holdings (holding_id, client_id, instrument_id, quantity, average_cost) VALUES (50, 50, 50, 0, 72.6000);



