package group12.Entities;

public enum OrderRejectionReason {
    INSTRUMENT_NOT_FOUND,
    INSTRUMENT_NOT_TRADABLE,
    MISSING_QUOTE,
    STALE_QUOTE,
    INSUFFICIENT_FUNDS,
    INSUFFICIENT_HOLDINGS
}
