package group12.Entities;

public enum OrderFailureReason {
    INSTRUMENT_NOT_FOUND,
    INSTRUMENT_NOT_TRADABLE,
    MARKET_QUOTE_TIMEOUT,
    INVALID_RESERVED_CASH,
    PRICE_EXCEEDS_RESERVED_CASH,
    INSUFFICIENT_ACTUAL_CASH,
    HOLDING_NOT_FOUND,
    INSUFFICIENT_HOLDINGS
}
